### PR TITLE
requirements.txt fix

### PR DESCRIPTION
**Pull request by Jensen-holm**
Also changed a few things so that it works right out of the box
- Removed lap as a dependency because of its issues with installing
- Changed the default videos directory to ./videos/videos1

### CODE REVIEW

**Comment by Jensen-holm** [comment]
with this fix, you can simply clone the repo, and run

1. `pip install -r requirements.txt`
2. `python3 pitching_overlay.py`

and then the program will run. With the older requirements.txt file you had to wrestle with python versions and pip versions in order to install lap and filterpy. But now it just works. In order to do this I had to completely remove lap from the _linear_assignment function in src/SORT_tracker/sort.py

**Comment by chonyy** [comment]
Thanks a lot for your contribution!

>  In order to do this I had to completely remove lap from the _linear_assignment function in src/SORT_tracker/sort.py

Could you let us know what would be the side effect of this decision? I personally didn't touch this project for 2-3 years so I am missing a lot of context now 😅. Thanks!

**Comment by Jensen-holm** [comment]
Yeah absolutley! So the _linear_assignment(cost_matrix) function in src/SORT_tracker/sort.py looked like this before hand:

```python

def linear_assignment(cost_matrix):
  try:
    import lap
    _, x, y = lap.lapjv(cost_matrix, extend_cost=True)
    return np.array([[y[i],i] for i in x if i >= 0]) #
  except ImportError:
    from scipy.optimize import linear_sum_assignment
    x, y = linear_sum_assignment(cost_matrix)
    return np.array(list(zip(x, y)))
```

I removed the try / except block and just used the scipy.optimize linear_sum_assignment function since lap was causing me some issues with installing the requirements easily with the `pip install -r requirements.txt` command.

So now the linear assignment function just looks like this:

```python

def linear_assignment(cost_matrix):
    x, y = linear_sum_assignment(cost_matrix)
    return np.array(list(zip(x, y)))
```

This way there is no issue with running `pip install -r requirements.txt` with python3.12

**Comment by Jensen-holm** [comment]
I moved the import statement `from scipy.optimize import linear_sum_assignment` to the top of the program. So essentially now we don't try to import the lap package, and just use the function from scipy instead.

**Comment by chonyy** [comment]
Thanks and LGTM!

**Pull request merged**
